version: '3.1'
services:
  mysql:
    restart: always
    image: mariadb:10.5
    command: ['mysqld','--character-set-server=utf8mb4','--ssl-ca=/etc/ssl/ca.pem','--ssl_cert=/etc/ssl/server-cert.pem','--ssl_key=/etc/ssl/server-key.pem']
    ports:
    - 8320:3306
    volumes:
    - ../development-insane/sql-ssl-certs-keys/easy/ca.pem:/etc/ssl/ca.pem:ro
    - ../development-insane/sql-ssl-certs-keys/easy/server-cert.pem:/etc/ssl/server-cert.pem:ro
    - ../development-insane/sql-ssl-certs-keys/easy/server-key.pem:/etc/ssl/server-key.pem:ro
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr/openemr:flex
    ports:
    - 8300:80
    - 9300:443
    volumes:
    - ../..:/openemr:ro
    - ../..:/var/www/localhost/htdocs/openemr:rw
    - publicvolume:/var/www/localhost/htdocs/openemr/public:rw
    - sitesvolume:/var/www/localhost/htdocs/openemr/sites:rw
    - nodemodules:/var/www/localhost/htdocs/openemr/node_modules:rw
    - vendordir:/var/www/localhost/htdocs/openemr/vendor:rw
    - ccdamodule:/var/www/localhost/htdocs/openemr/ccdaservice:rw
    - logvolume:/var/log
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
      EASY_DEV_MODE: "yes"
      EASY_DEV_MODE_NEW: "yes"
      DEVELOPER_TOOLS: "yes"
      XDEBUG_IDE_KEY: PHPSTORM
      XDEBUG_PROFILER_ON: 1
      GITHUB_COMPOSER_TOKEN: c313de1ed5a00eb6ff9309559ec9ad01fcc553f0
      OPENEMR_DOCKER_ENV_TAG: easy-dev-docker
      OPENEMR_SETTING_site_addr_oath: 'https://localhost:9300'
      OPENEMR_SETTING_oauth_password_grant: 3
      OPENEMR_SETTING_rest_api: 1
      OPENEMR_SETTING_rest_fhir_api: 1
      OPENEMR_SETTING_rest_portal_api: 1
      OPENEMR_SETTING_rest_portal_fhir_api: 1
      OPENEMR_SETTING_portal_onsite_two_enable: 1
      OPENEMR_SETTING_ccda_alt_service_enable: 3
    depends_on:
    - mysql
  phpmyadmin:
    restart: always
    image: phpmyadmin
    ports:
    - 8310:80
    environment:
      PMA_HOSTS: mysql
volumes:
  databasevolume: {}
  publicvolume: {}
  sitesvolume: {}
  nodemodules: {}
  vendordir: {}
  ccdamodule: {}
  logvolume: {}
